# Due to the following error, we have to manually copy paste contracts from Open Zeppelin
# error: Version solving failed:
# - openzeppelin v0.7.0 (git+https:#github.com/OpenZeppelin/cairo-contracts.git?tag=v0.7.0#61a2505fe0c0f19b5de2b3f8dedf421ba2cff657) cannot use starknet v2.3.0-rc0 (std), because openzeppelin requires starknet >=2.2.0

# Scarb does not have real version solving algorithm yet.
# Perhaps in the future this conflict could be resolved, but currently,
# please upgrade your dependencies to use latest versions of their dependencies.
#
#
# Credits: "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0"


[package]
name = "openzeppelin"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true

[tool]
fmt.workspace = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }
assert_macros = "2.8.2"

[scripts]
test = "snforge test --max-n-steps 4294967295"
test-profiling = "snforge test --max-n-steps 4294967295 --build-profile"
